# Generated by Django 4.2.8 on 2026-02-13 23:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Rota')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em Andamento'), ('concluída', 'Concluída'), ('cancelada', 'Cancelada')], default='planejamento', max_length=20, verbose_name='Status')),
                ('distancia_total', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distância Total (km)')),
                ('tempo_total', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo Total (min)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RotaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='rotas.rota')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Rota',
                'verbose_name_plural': 'Históricos de Rotas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField(default=0, verbose_name='Sequência')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('cliente_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('endereco', models.CharField(max_length=500, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('tipo', models.CharField(choices=[('coleta', 'Coleta'), ('entrega', 'Entrega'), ('devolução', 'Devolução'), ('transferência', 'Transferência')], default='entrega', max_length=20, verbose_name='Tipo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('tempo_estimado', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo Estimado (min)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='rotas.rota')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['rota', 'sequencia'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao_padrao_lat', models.FloatField(default=0.034987, verbose_name='Latitude Padrão')),
                ('localizacao_padrao_lng', models.FloatField(default=-51.074846, verbose_name='Longitude Padrão')),
                ('nome_empresa', models.CharField(default='FERMAP Logística', max_length=255, verbose_name='Nome da Empresa')),
                ('telefone_empresa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Empresa')),
                ('email_empresa', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Empresa')),
                ('usar_otimizacao_automatica', models.BooleanField(default=True, verbose_name='Otimização Automática')),
                ('permitir_compartilhamento', models.BooleanField(default=False, verbose_name='Permitir Compartilhamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_logistica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Usuário',
                'verbose_name_plural': 'Configurações de Usuários',
            },
        ),
        migrations.AddIndex(
            model_name='rota',
            index=models.Index(fields=['usuario', '-data_criacao'], name='rotas_rota_usuario_fd17c8_idx'),
        ),
        migrations.AddIndex(
            model_name='rota',
            index=models.Index(fields=['status'], name='rotas_rota_status_fc0ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='parada',
            index=models.Index(fields=['rota', 'sequencia'], name='rotas_parad_rota_id_11a339_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parada',
            unique_together={('rota', 'sequencia')},
        ),
    ]
