# Generated by Django 4.2.8 on 2026-02-14 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexaoFirebird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conexao', models.CharField(max_length=255, verbose_name='Nome da Conexão')),
                ('host', models.CharField(help_text='IP ou nome do servidor', max_length=255, verbose_name='Host/Servidor')),
                ('porta', models.IntegerField(default=3050, verbose_name='Porta')),
                ('caminho_banco', models.CharField(help_text='Ex: C:\\Firebird\\database.fdb ou /home/user/database.fdb', max_length=500, verbose_name='Caminho do Banco')),
                ('usuario_banco', models.CharField(default='SYSDBA', max_length=100, verbose_name='Usuário Firebird')),
                ('senha_banco', models.CharField(max_length=255, verbose_name='Senha Firebird')),
                ('charset', models.CharField(default='UTF8', max_length=50, verbose_name='Charset')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('testado', models.BooleanField(default=False, verbose_name='Conexão Testada')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conexao_firebird', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão Firebird',
                'verbose_name_plural': 'Conexões Firebird',
            },
        ),
        migrations.CreateModel(
            name='QueryFirebird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_query', models.CharField(max_length=255, verbose_name='Nome da Query')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('sql', models.TextField(help_text='Query SQL para buscar pedidos e clientes', verbose_name='SQL Query')),
                ('campo_pedido', models.CharField(help_text='Nome da coluna no resultado', max_length=100, verbose_name='Campo: Número do Pedido')),
                ('campo_cliente', models.CharField(help_text='Nome da coluna no resultado', max_length=100, verbose_name='Campo: Nome do Cliente')),
                ('campo_entregador', models.CharField(blank=True, help_text='Nome da coluna no resultado (opcional)', max_length=100, null=True, verbose_name='Campo: Entregador')),
                ('campo_latitude', models.CharField(help_text='Nome da coluna no resultado', max_length=100, verbose_name='Campo: Latitude')),
                ('campo_longitude', models.CharField(help_text='Nome da coluna no resultado', max_length=100, verbose_name='Campo: Longitude')),
                ('campo_descricao', models.CharField(blank=True, help_text='Nome da coluna no resultado (opcional)', max_length=100, null=True, verbose_name='Campo: Descrição')),
                ('campo_endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Endereço')),
                ('campo_telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Telefone')),
                ('campo_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Email')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('conexao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='rotas.conexaofirebird')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries_firebird', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Query Firebird',
                'verbose_name_plural': 'Queries Firebird',
            },
        ),
        migrations.CreateModel(
            name='PedidoFirebird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=100, verbose_name='Número do Pedido')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('entregador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Entregador')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('endereco', models.CharField(blank=True, max_length=500, null=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('dados_json', models.JSONField(blank=True, default=dict, verbose_name='Dados Completos')),
                ('importado', models.BooleanField(default=False, verbose_name='Importado para Rota')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='rotas.queryfirebird')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_firebird', to='rotas.rota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_firebird', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido Firebird',
                'verbose_name_plural': 'Pedidos Firebird',
                'unique_together': {('usuario', 'numero_pedido', 'query')},
            },
        ),
    ]
