# Generated by Django 4.2.8 on 2026-02-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0002_conexaofirebird_queryfirebird_pedidofirebird'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_descricao',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_email',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_entregador',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_telefone',
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_bairro_cobranca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Bairro Cobrança'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Bairro Cliente'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_celular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Celular Cliente'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_cep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: CEP Cliente'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Cidade Cliente'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Complemento'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_cpfcnpj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: CPF/CNPJ Cliente'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Email Cliente'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Estado Cliente'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_fantasia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Fantasia Cliente'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_numero',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Número Endereço'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_rgie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: RG/IE Cliente'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_cliente_telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Telefone Cliente'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_data_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Data Previsão Entrega'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_data_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Data do Pedido'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_empresa_cnpj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: CNPJ Empresa'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_empresa_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Nome Empresa'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_empresa_telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Telefone Empresa'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_endereco_cobranca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Endereço Cobrança'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_numero_cobranca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Número Cobrança'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_observacao_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Observação'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_produto_codigo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Código Produto'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_produto_descricao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Descrição Produto'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_produto_quantidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Quantidade'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_produto_valor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Valor Produto'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_status_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Status Pedido'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_valor_pedido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Valor do Pedido'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_vendedor_codigo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Código Vendedor'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_vendedor_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Nome Vendedor'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='mapeamento_adicional',
            field=models.JSONField(blank=True, default=dict, help_text='Mapeamentos extras de campos personalizados', verbose_name='Mapeamento Adicional'),
        ),
        migrations.AlterField(
            model_name='queryfirebird',
            name='campo_cliente',
            field=models.CharField(help_text='Ex: Nome cliente', max_length=100, verbose_name='Campo: Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='queryfirebird',
            name='campo_endereco',
            field=models.CharField(blank=True, help_text='Ex: Endereco cliente', max_length=100, null=True, verbose_name='Campo: Endereço'),
        ),
        migrations.AlterField(
            model_name='queryfirebird',
            name='campo_latitude',
            field=models.CharField(help_text='Ex: LATITUDE', max_length=100, verbose_name='Campo: Latitude'),
        ),
        migrations.AlterField(
            model_name='queryfirebird',
            name='campo_longitude',
            field=models.CharField(help_text='Ex: LONGITUDE', max_length=100, verbose_name='Campo: Longitude'),
        ),
        migrations.AlterField(
            model_name='queryfirebird',
            name='campo_pedido',
            field=models.CharField(help_text='Ex: PEDIDO', max_length=100, verbose_name='Campo: Número do Pedido'),
        ),
    ]
