# Generated by Django 4.2.8 on 2026-02-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0003_remove_queryfirebird_campo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidofirebird',
            options={'ordering': ['-data_importacao'], 'verbose_name': 'Pedido Firebird', 'verbose_name_plural': 'Pedidos Firebird'},
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='entregador',
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='bairro_cobranca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro Cobrança'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='cliente_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Cliente'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='cliente_cpfcnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='cliente_rgie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG/IE'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='data_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrega'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='data_pedido',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pedido'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='endereco_cobranca',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Endereço Cobrança'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='numero_cobranca',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número Cobrança'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='numero_endereco',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='regiao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='valor_pedido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Pedido'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='vendedor_codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Vendedor'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='vendedor_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Vendedor'),
        ),
        migrations.AlterField(
            model_name='pedidofirebird',
            name='numero_pedido',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Número do Pedido'),
        ),
        migrations.AddIndex(
            model_name='pedidofirebird',
            index=models.Index(fields=['usuario', 'importado'], name='rotas_pedid_usuario_dd3425_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidofirebird',
            index=models.Index(fields=['data_pedido'], name='rotas_pedid_data_pe_de8beb_idx'),
        ),
    ]
