# Generated by Django 4.2.8 on 2026-02-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0004_alter_pedidofirebird_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='ponto_final_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude Ponto Final'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='ponto_final_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude Ponto Final'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='ponto_partida_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude Ponto de Partida'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='ponto_partida_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude Ponto de Partida'),
        ),
    ]
