# Generated by Django 4.2.8 on 2026-02-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0005_configuracaousuario_ponto_final_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='campos_exibicao_pedidos',
            field=models.JSONField(blank=True, default=list, help_text='Lista ordenada dos campos que devem ser exibidos no painel de pedidos', verbose_name='Campos de Exibição de Pedidos'),
        ),
    ]
