# Generated by Django 4.2.8 on 2026-02-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0006_configuracaousuario_campos_exibicao_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='pedidos_card_cor_borda',
            field=models.CharField(default='#e9ecef', max_length=7, verbose_name='Cor da Borda do Card'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='pedidos_card_cor_fundo',
            field=models.CharField(default='#f8f9fa', max_length=7, verbose_name='Cor de Fundo do Card'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='pedidos_card_cor_texto',
            field=models.CharField(default='#666666', max_length=7, verbose_name='Cor do Texto do Card'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='pedidos_card_padding',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Padding do Card'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='pedidos_card_raio',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Raio de Borda do Card'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='pedidos_card_tamanho_fonte',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='Tamanho da Fonte do Card'),
        ),
    ]
