# Generated by Django 4.2.8 on 2026-02-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0007_configuracaousuario_pedidos_card_cor_borda_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidofirebird',
            options={'verbose_name': 'Pedido Firebird', 'verbose_name_plural': 'Pedidos Firebird'},
        ),
        migrations.RemoveIndex(
            model_name='pedidofirebird',
            name='rotas_pedid_usuario_dd3425_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidofirebird',
            name='rotas_pedid_data_pe_de8beb_idx',
        ),
        migrations.RemoveField(
            model_name='configuracaousuario',
            name='pedidos_card_cor_texto',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='bairro_cobranca',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='cliente_codigo',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='cliente_cpfcnpj',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='cliente_rgie',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='data_pedido',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='endereco_cobranca',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='numero_cobranca',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='numero_endereco',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='regiao',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='valor_pedido',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='vendedor_codigo',
        ),
        migrations.RemoveField(
            model_name='pedidofirebird',
            name='vendedor_nome',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_bairro_cobranca',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_bairro',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_celular',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_cep',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_cidade',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_complemento',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_cpfcnpj',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_email',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_estado',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_fantasia',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_numero',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_rgie',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_cliente_telefone',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_data_entrega',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_data_pedido',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_empresa_cnpj',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_empresa_nome',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_empresa_telefone',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_endereco_cobranca',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_numero_cobranca',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_observacao_pedido',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_produto_codigo',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_produto_descricao',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_produto_quantidade',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_produto_valor',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_status_pedido',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_valor_pedido',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_vendedor_codigo',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='campo_vendedor_nome',
        ),
        migrations.RemoveField(
            model_name='queryfirebird',
            name='mapeamento_adicional',
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='pedidos_card_padding_horizontal',
            field=models.IntegerField(default=8, verbose_name='Padding Horizontal do Card'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='pedidos_card_padding_vertical',
            field=models.IntegerField(default=8, verbose_name='Padding Vertical do Card'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='pedidos_panel_largura',
            field=models.IntegerField(default=320, verbose_name='Largura do Painel de Pedidos (px)'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='permitir_pedidos_sem_coordenadas',
            field=models.BooleanField(default=True, verbose_name='Permitir pedidos sem coordenadas na rota'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='pedidofirebird',
            name='entregador',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entregador'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_descricao',
            field=models.CharField(blank=True, help_text='Nome da coluna no resultado (opcional)', max_length=100, null=True, verbose_name='Campo: Descrição'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Email'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_entregador',
            field=models.CharField(blank=True, help_text='Nome da coluna no resultado (opcional)', max_length=100, null=True, verbose_name='Campo: Entregador'),
        ),
        migrations.AddField(
            model_name='queryfirebird',
            name='campo_telefone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Telefone'),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='campos_exibicao_pedidos',
            field=models.JSONField(blank=True, default=list, verbose_name='Campos de Exibição dos Pedidos'),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='pedidos_card_cor_borda',
            field=models.CharField(default='#e0e0e0', max_length=20, verbose_name='Cor da Borda do Card'),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='pedidos_card_cor_fundo',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Cor de Fundo do Card'),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='pedidos_card_padding',
            field=models.IntegerField(default=8, verbose_name='Padding do Card'),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='pedidos_card_raio',
            field=models.IntegerField(default=8, verbose_name='Raio da Borda do Card'),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='pedidos_card_tamanho_fonte',
            field=models.IntegerField(default=12, verbose_name='Tamanho da Fonte do Card'),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='ponto_final_lat',
            field=models.FloatField(default=0.034987, verbose_name='Ponto Final - Latitude'),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='ponto_final_lng',
            field=models.FloatField(default=-51.074846, verbose_name='Ponto Final - Longitude'),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='ponto_partida_lat',
            field=models.FloatField(default=0.034987, verbose_name='Ponto de Partida - Latitude'),
        ),
        migrations.AlterField(
            model_name='configuracaousuario',
            name='ponto_partida_lng',
            field=models.FloatField(default=-51.074846, verbose_name='Ponto de Partida - Longitude'),
        ),
        migrations.AlterField(
            model_name='pedidofirebird',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='pedidofirebird',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='pedidofirebird',
            name='numero_pedido',
            field=models.CharField(max_length=100, verbose_name='Número do Pedido'),
        ),
        migrations.AlterField(
            model_name='queryfirebird',
            name='campo_cliente',
            field=models.CharField(help_text='Nome da coluna no resultado', max_length=100, verbose_name='Campo: Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='queryfirebird',
            name='campo_endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo: Endereço'),
        ),
        migrations.AlterField(
            model_name='queryfirebird',
            name='campo_latitude',
            field=models.CharField(help_text='Nome da coluna no resultado', max_length=100, verbose_name='Campo: Latitude'),
        ),
        migrations.AlterField(
            model_name='queryfirebird',
            name='campo_longitude',
            field=models.CharField(help_text='Nome da coluna no resultado', max_length=100, verbose_name='Campo: Longitude'),
        ),
        migrations.AlterField(
            model_name='queryfirebird',
            name='campo_pedido',
            field=models.CharField(help_text='Nome da coluna no resultado', max_length=100, verbose_name='Campo: Número do Pedido'),
        ),
    ]
