# Generated by Django 4.2.8 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0008_alter_pedidofirebird_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='pedidos_card_regras_cor',
            field=models.JSONField(blank=True, default=list, verbose_name='Regras de Cor dos Cards'),
        ),
    ]
