# Generated by Django 4.2.8 on 2026-02-15 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rotas', '0009_configuracaousuario_pedidos_card_regras_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Template')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('titulo_documento', models.CharField(default='🚛 Rota de Entrega', max_length=255, verbose_name='Título do Documento')),
                ('mostrar_data', models.BooleanField(default=True, verbose_name='Mostrar Data')),
                ('mostrar_distancia', models.BooleanField(default=True, verbose_name='Mostrar Distância')),
                ('mostrar_tempo', models.BooleanField(default=True, verbose_name='Mostrar Tempo')),
                ('mostrar_total_paradas', models.BooleanField(default=True, verbose_name='Mostrar Total de Paradas')),
                ('cabecalho_personalizado', models.TextField(blank=True, null=True, verbose_name='Cabeçalho Personalizado')),
                ('rodape_personalizado', models.TextField(blank=True, null=True, verbose_name='Rodapé Personalizado')),
                ('cor_cabecalho_tabela', models.CharField(default='#4285F4', max_length=7, verbose_name='Cor do Cabeçalho da Tabela')),
                ('cor_fundo_linhas', models.CharField(default='#F5F5DC', max_length=7, verbose_name='Cor de Fundo das Linhas')),
                ('campos_paradas', models.JSONField(blank=True, default=list, help_text='Lista de campos a exibir: sequencia, cliente_nome, endereco, telefone, observacoes, etc.', verbose_name='Campos das Paradas')),
                ('larguras_colunas', models.JSONField(blank=True, default=list, help_text='Lista de larguras proporcionais para cada coluna', verbose_name='Larguras das Colunas')),
                ('campos_sql_extras', models.JSONField(blank=True, default=list, help_text='Campos adicionais do SQL a serem exibidos', verbose_name='Campos SQL Extras')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_pdf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template PDF',
                'verbose_name_plural': 'Templates PDF',
                'ordering': ['-data_modificacao'],
            },
        ),
    ]
