# Generated by Django 4.2.8 on 2026-02-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0010_templatepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_cor_borda',
            field=models.CharField(default='#dadce0', max_length=20, verbose_name='Cor da Borda do Card de Rota'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_cor_fundo',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Cor de Fundo do Card de Rota'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_cor_numero',
            field=models.CharField(default='#4285F4', max_length=20, verbose_name='Cor do Número da Sequência'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_mostrar_endereco',
            field=models.BooleanField(default=True, verbose_name='Mostrar Endereço'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_mostrar_numero',
            field=models.BooleanField(default=True, verbose_name='Mostrar Número da Sequência'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_mostrar_obs',
            field=models.BooleanField(default=True, verbose_name='Mostrar Observações'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_padding_horizontal',
            field=models.IntegerField(default=12, verbose_name='Padding Horizontal do Card de Rota'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_padding_vertical',
            field=models.IntegerField(default=12, verbose_name='Padding Vertical do Card de Rota'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_raio',
            field=models.IntegerField(default=8, verbose_name='Raio da Borda do Card de Rota'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_tamanho_fonte',
            field=models.IntegerField(default=13, verbose_name='Tamanho da Fonte do Card de Rota'),
        ),
    ]
