# Generated by Django 4.2.8 on 2026-02-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0011_configuracaousuario_rotas_card_cor_borda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='campos_exibicao_rotas',
            field=models.JSONField(blank=True, default=list, verbose_name='Campos de Exibição dos Cards de Rota'),
        ),
    ]
