# Generated by Django 4.2.8 on 2026-02-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0012_configuracaousuario_campos_exibicao_rotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='rotas_card_regras_cor',
            field=models.JSONField(blank=True, default=list, verbose_name='Regras de Cor dos Cards de Rota'),
        ),
    ]
