# Generated by Django 4.2.8 on 2026-02-20 22:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rotas', '0013_configuracaousuario_rotas_card_regras_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Layout')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(default=False, verbose_name='Usar como Padrão')),
                ('page_size', models.CharField(choices=[('A4', 'A4 (210mm x 297mm)'), ('Letter', 'Letter (8.5" x 11")'), ('Legal', 'Legal (8.5" x 14")'), ('A3', 'A3 (297mm x 420mm)'), ('A5', 'A5 (148mm x 210mm)')], default='A4', max_length=20, verbose_name='Tamanho da Página')),
                ('orientation', models.CharField(choices=[('portrait', 'Retrato'), ('landscape', 'Paisagem')], default='portrait', max_length=20, verbose_name='Orientação')),
                ('margin_top', models.FloatField(default=20.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Margem Superior (mm)')),
                ('margin_bottom', models.FloatField(default=20.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Margem Inferior (mm)')),
                ('margin_left', models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Margem Esquerda (mm)')),
                ('margin_right', models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Margem Direita (mm)')),
                ('default_font_family', models.CharField(default='Helvetica', max_length=100, verbose_name='Fonte Padrão')),
                ('default_font_size', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tamanho da Fonte Padrão')),
                ('layout_json', models.JSONField(blank=True, default=dict, help_text='Estrutura JSON com bandas e elementos', verbose_name='Configuração do Layout')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('versao', models.IntegerField(default=1, verbose_name='Versão')),
                ('query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layouts', to='rotas.queryfirebird', verbose_name='Query de Dados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Layout de Relatório',
                'verbose_name_plural': 'Layouts de Relatórios',
                'ordering': ['-data_modificacao'],
            },
        ),
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('total_paginas', models.IntegerField(default=0)),
                ('tempo_geracao', models.FloatField(blank=True, help_text='Tempo em segundos', null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='rotas.layoutreport')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rotas.rota')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Relatório',
                'verbose_name_plural': 'Históricos de Relatórios',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.AddIndex(
            model_name='layoutreport',
            index=models.Index(fields=['usuario', 'ativo'], name='rotas_layou_usuario_22161e_idx'),
        ),
        migrations.AddIndex(
            model_name='layoutreport',
            index=models.Index(fields=['padrao'], name='rotas_layou_padrao_b19186_idx'),
        ),
    ]
