# Generated by Django 4.2.8 on 2026-02-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0014_layoutreport_reporthistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='permitir_pedido_multiplas_rotas',
            field=models.BooleanField(default=False, verbose_name='Permitir mesmo pedido em múltiplas rotas'),
        ),
    ]
