# Generated by Django 4.2.8 on 2026-03-01 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rotas', '0017_pedidofirebird_arquivado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('produtos', 'Produtos por Pedido'), ('personalizado', 'Personalizado')], default='personalizado', max_length=50, verbose_name='Tipo')),
                ('sql', models.TextField(verbose_name='SQL')),
                ('campo_join_pedido', models.CharField(blank=True, help_text='Nome da coluna no resultado que contém o número do pedido (para vincular ao pedido principal)', max_length=100, null=True, verbose_name='Campo de Ligação (Pedido)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('conexao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqls_extra', to='rotas.conexaofirebird', verbose_name='Conexão Firebird')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sqls_extra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SQL Extra',
                'verbose_name_plural': 'SQLs Extra',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
