# Generated by Django 4.2.8 on 2026-03-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0018_add_sqlextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='ponto_final_ativo',
            field=models.BooleanField(default=False, verbose_name='Usar Ponto Final Fixo'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='ponto_partida_ativo',
            field=models.BooleanField(default=False, verbose_name='Usar Ponto de Partida Fixo'),
        ),
    ]
