# Generated by Django 4.2.8 on 2026-03-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0019_add_ponto_fixo_ativo_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='ponto_final_nome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ponto Final - Nome'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='ponto_partida_nome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ponto de Partida - Nome'),
        ),
    ]
