# Generated by Django 4.2.8 on 2026-03-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0020_add_ponto_fixo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaousuario',
            name='ors_api_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Chave API OpenRouteService'),
        ),
        migrations.AddField(
            model_name='configuracaousuario',
            name='otimizacao_motor',
            field=models.CharField(choices=[('local', 'Local (B&B)'), ('vroom', 'Vroom'), ('ors', 'OpenRouteService')], default='local', max_length=10, verbose_name='Motor de Otimização'),
        ),
    ]
