# Generated by Django 4.2.8 on 2026-03-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0027_historicoexclusaopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlextra',
            name='campos_join',
            field=models.JSONField(blank=True, default=list, help_text='Lista de pares [{"coluna_sql": "...", "campo_pedido": "..."}] para vincular ao pedido.', verbose_name='Campos de Ligação'),
        ),
        migrations.AlterField(
            model_name='configuracaoglobal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sqlextra',
            name='campo_join_pedido',
            field=models.CharField(blank=True, help_text='(Deprecated) Use campos_join. Nome da coluna que contém o nº do pedido.', max_length=100, null=True, verbose_name='Campo de Ligação (Pedido)'),
        ),
    ]
