# Generated by Django 4.2.8 on 2026-03-21 19:22

from django.db import migrations


def convert_campo_join_to_campos_join(apps, schema_editor):
    """Converte campo_join_pedido (CharField) existente para campos_join (JSONField)."""
    SqlExtra = apps.get_model('rotas', 'SqlExtra')
    for obj in SqlExtra.objects.exclude(campo_join_pedido__isnull=True).exclude(campo_join_pedido=''):
        if not obj.campos_join:  # Só converte se campos_join ainda vazio
            obj.campos_join = [{'coluna_sql': obj.campo_join_pedido, 'campo_pedido': 'numero_pedido'}]
            obj.save(update_fields=['campos_join'])


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0028_add_campos_join_to_sqlextra'),
    ]

    operations = [
        migrations.RunPython(convert_campo_join_to_campos_join, migrations.RunPython.noop),
    ]
