# Generated by Django 4.2.8 on 2026-03-21 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rotas', '0029_migrate_campo_join_to_campos_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaioXAba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Aba')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('tipo', models.CharField(choices=[('dados_pedido', 'Dados do Pedido'), ('sql', 'Consulta SQL'), ('texto', 'Texto Livre')], default='sql', max_length=20, verbose_name='Tipo')),
                ('campos_join', models.JSONField(blank=True, default=list, verbose_name='Parâmetros de Ligação')),
                ('kpis_config', models.JSONField(blank=True, default=list, verbose_name='Configuração de KPIs')),
                ('colunas_visiveis', models.JSONField(blank=True, default=list, verbose_name='Colunas Visíveis')),
                ('grafico_config', models.JSONField(blank=True, default=dict, verbose_name='Configuração de Gráfico')),
                ('componentes_ordem', models.JSONField(blank=True, default=list, verbose_name='Ordem dos Componentes')),
                ('texto', models.TextField(blank=True, verbose_name='Texto Livre')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('sql_extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raio_x_abas', to='rotas.sqlextra', verbose_name='SQL Extra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raio_x_abas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aba do Raio X',
                'verbose_name_plural': 'Abas do Raio X',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
