# Generated by Django 4.2.8 on 2026-03-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0030_raiox_aba'),
    ]

    operations = [
        migrations.AddField(
            model_name='raioxaba',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Layout do Dashboard'),
        ),
    ]